sudo: required
os: linux
dist: trusty

services:
  - docker

language: java

matrix:
  include:
    - stage : Build
      jdk: openjdk7
      if: tag IS present
      script:
        - wget https://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.zip
        - unzip -qq apache-maven-3.1.1-bin.zip
        - export M2_HOME=$PWD/apache-maven-3.1.1
        - export PATH=$M2_HOME/bin:$PATH
        - bash ./scripts/travis-deploy.sh
    -
      jdk: oraclejdk8
      if: tag IS present
      script:
        - wget https://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.zip
        - unzip -qq apache-maven-3.1.1-bin.zip
        - export M2_HOME=$PWD/apache-maven-3.1.1
        - export PATH=$M2_HOME/bin:$PATH
        - bash ./scripts/travis-deploy.sh
    - stage : Update
      if: tag IS NOT present
      script:
        - bash ./scripts/keepSync.sh

before_deploy:
  - echo "Now deploying things !"
  - git config --local user.name "Villena Guillaume"
  - git config --local user.email "guiguivil@gmail.com"
  - source VERSION

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

deploy:
  provider: releases
  api_key: $GH_TOKEN
  overwrite: true
  file_glob: true
  file: /home/travis/build/Willena/sqlite-jdbc-crypt/target/sqlite-jdbc-*-SNAPSHOT.jar
  skip_cleanup: true
  name: SQLite-jdbc-$version
  on:
    tags: true
