name: build
on:
  push:
    branches:
      - '**'
jobs:
  build_natives:
    name: Build natives libraries
    runs-on: ubuntu-20.04
    steps:
      - name: Install required tools
        run: |
          sudo apt install curl make jq xmlstarlet gnupg wget
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          java-package: jdk
          cache: 'maven'
      - name: Build all natives
        run: make jni-header native-all
